---
- name: Create the OpenStack resources for cluster installation
<<<<<<< HEAD
  import_playbook: provision_resources.yml
=======
  hosts: localhost
  tasks:
  - name: provision cluster
    import_role:
      name: openshift_openstack
      tasks_from: provision.yml

>>>>>>> Migrate to import_role for static role inclusion

<<<<<<< HEAD
- name: Evaluate OpenStack groups from the dynamic inventory
  import_playbook: evaluate_groups.yml
=======
# NOTE(shadower): Bring in the host groups:
- name: evaluate groups
  import_playbook: ../../init/evaluate_groups.yml
>>>>>>> Include Deprecation: Convert to import_playbook

- name: Evaluate remaining cluster groups
  import_playbook: ../../init/evaluate_groups.yml

- name: Wait for the nodes and gather their facts
  any_errors_fatal: true
  hosts: oo_all_hosts
  become: yes
  # NOTE: The nodes may not be up yet, don't gather facts here.
  # They'll be collected after `wait_for_connection`.
  gather_facts: no
  tasks:
  - name: Wait for the nodes to come up
    wait_for_connection:

  - name: Gather facts for the new nodes
    setup:

<<<<<<< HEAD
=======
- name: set common facts
  import_playbook: ../../init/facts.yml

>>>>>>> Fix and cleanup not required dns bits

# TODO(shadower): consider splitting this up so people can stop here
# and configure their DNS if they have to.
- name: Populate the DNS entries
  any_errors_fatal: true
  hosts: localhost
  tasks:
<<<<<<< HEAD
  - name: Add the DNS records
=======
  - name: Populate DNS entries
>>>>>>> Migrate to import_role for static role inclusion
    import_role:
      name: openshift_openstack
      tasks_from: populate-dns.yml
    vars:
      l_openshift_openstack_dns_update_nodes: "{{ groups.OSEv3 }}"
    when:
    - openshift_openstack_external_nsupdate_keys is defined
    - openshift_openstack_external_nsupdate_keys.private is defined or openshift_openstack_external_nsupdate_keys.public is defined


- import_playbook: ../../init/basic_facts.yml

- name: Run the init
  import_playbook: ../../init/main.yml

- name: Optionally subscribe the RHEL nodes
  any_errors_fatal: true
  hosts: oo_all_hosts
  become: yes
  gather_facts: yes
  tasks:
  - name: Subscribe RHEL instances
    import_role:
      name: rhel_subscribe
    when:
    - ansible_distribution == "RedHat"
    - (rhsub_user is defined and rhsub_pass is defined) or (rhsub_ak is defined and rhsub_orgid is defined)

<<<<<<< HEAD
  - name: Configuring proper repositories
=======
  - name: Enable required YUM repositories
>>>>>>> Migrate to import_role for static role inclusion
    import_role:
      name: openshift_repos
    when:
    - ansible_distribution == "RedHat"
    - (rhsub_user is defined and rhsub_pass is defined) or (rhsub_ak is defined and rhsub_orgid is defined)

<<<<<<< HEAD
- name: Show information about the deployed cluster
  import_playbook: cluster-info.yml
=======
  - name: Install dependencies
    import_role:
      name: openshift_openstack
      tasks_from: node-packages.yml

  - name: Configure Node
    import_role:
      name: openshift_openstack
      tasks_from: node-configuration.yml
>>>>>>> Migrate to import_role for static role inclusion
