---
- name: setup firewall
  import_tasks: firewall.yml

- name: Install cockpit-ws
  package:
    name: "{{ pkg_list | join(',') }}"
    state: present
  vars:
    pkg_list:
    - cockpit-ws
    - cockpit-system
    - cockpit-bridge
    - cockpit-docker
<<<<<<< HEAD
    - "{{ cockpit_plugins | join(',') }}"
  register: result
  until: result is succeeded
=======
    - "{{ cockpit_plugins }}"
  when: not openshift.common.is_containerized | bool
  register: result
<<<<<<< HEAD
  until: result | success
>>>>>>> retry package operations
=======
  until: result is succeeded
>>>>>>> Deprecate using Ansible tests as filters

- name: Enable cockpit-ws
  systemd:
    name: cockpit.socket
    enabled: true
    state: started
