---
- name: Update master count
  hosts: oo_masters:!oo_masters_to_config
  serial: 1
  tasks:
  - name: Update master count
<<<<<<< HEAD
    import_role:
      name: openshift_control_plane
      tasks_from: update_master_count.yml
=======
    modify_yaml:
      dest: "{{ openshift.common.config_base}}/master/master-config.yaml"
      yaml_key: 'kubernetesMasterConfig.masterCount'
      yaml_value: "{{ openshift.master.master_count }}"
    notify:
    - restart master api
    - restart master controllers
  handlers:
  - name: restart master api
    service: name={{ openshift_service_type }}-master-controllers state=restarted
    notify: verify api server
  # We retry the controllers because the API may not be 100% initialized yet.
  - name: restart master controllers
    command: "systemctl restart {{ openshift_service_type }}-master-controllers"
    retries: 3
    delay: 5
    register: result
    until: result.rc == 0
  - name: verify api server
    command: >
      curl --silent --tlsv1.2
      --cacert {{ openshift.common.config_base }}/master/ca-bundle.crt
      {{ openshift.master.api_url }}/healthz/ready
    args:
      # Disables the following warning:
      # Consider using get_url or uri module rather than running curl
      warn: no
    register: api_available_output
    until: api_available_output.stdout == 'ok'
    retries: 120
    delay: 1
    changed_when: false
>>>>>>> Remove openshift.common.service_type

- import_playbook: ../../openshift-node/private/bootstrap.yml

- import_playbook: ../../openshift-etcd/private/master_etcd_certificates.yml

- import_playbook: config.yml

- import_playbook: ../../openshift-node/private/join.yml

- import_playbook: ../../openshift-loadbalancer/private/config.yml

- import_playbook: ../../openshift-glusterfs/private/add_hosts.yml
