---
- import_playbook: ../init/evaluate_groups.yml

- name: Subscribe hosts, update repos and update OS packages
  hosts: oo_all_hosts
  roles:
  - role: rhel_subscribe
    when:
    - openshift_deployment_type == 'openshift-enterprise'
    - ansible_distribution == "RedHat"
<<<<<<< HEAD
    - (rhsub_user is defined and rhsub_pass is defined) or (rhsub_ak is defined and rhsub_orgid is defined)
=======
    - rhsub_user | default(False)
    - rhsub_pass | default(False)
>>>>>>> Move repo and subscribe to prerequisites
  - role: openshift_repos
  - role: os_update_latest
