---
- name: nickhammond.logrotate | Install logrotate
<<<<<<< HEAD
  package:
    name: logrotate
    state: present
  register: result
  until: result is succeeded
=======
  package: name=logrotate state=present
  when: not openshift.common.is_atomic | bool
  register: result
<<<<<<< HEAD
  until: result | success
>>>>>>> retry package operations
=======
  until: result is succeeded
>>>>>>> Deprecate using Ansible tests as filters

- name: nickhammond.logrotate | Setup logrotate.d scripts
  template:
    src: logrotate.d.j2
    dest: /etc/logrotate.d/{{ item.name }}
  with_items: "{{ logrotate_scripts | default([]) }}"
  when: logrotate_scripts is defined
