---
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
# TODO: Enhance redhat_subscription module
#       to make it able to attach to a pool
#       to make it able to enable repositories
=======
=======
>>>>>>> Move repo and subscribe to prerequisites
- set_fact:
    rhel_subscription_pass: "{{ lookup('env', 'rhel_subscription_pass') | default(rhsub_pass | default(omit, True)) }}"
    rhel_subscription_pool: "{{ lookup('env', 'rhel_subscription_pool') | default(rhsub_pool | default('Red Hat OpenShift Container Platform, Premium*')) }}"
    rhel_subscription_user: "{{ lookup('env', 'rhel_subscription_user') | default(rhsub_user | default(omit, True)) }}"
    rhel_subscription_server: "{{ lookup('env', 'rhel_subscription_server') | default(rhsub_server | default(omit, True)) }}"
>>>>>>> Commit to stabalize RHSM operations.  This code is derived from contrib

<<<<<<< HEAD
- set_fact:
    rhel_subscription_pool: "{{ lookup('env', 'rhel_subscription_pool') | default(rhsub_pool | default('Red Hat OpenShift Container Platform, Premium*')) }}"
    rhel_subscription_user: "{{ lookup('env', 'rhel_subscription_user') | default(rhsub_user | default(omit, True)) }}"
    rhel_subscription_pass: "{{ lookup('env', 'rhel_subscription_pass') | default(rhsub_pass | default(omit, True)) }}"
    rhel_subscription_server: "{{ lookup('env', 'rhel_subscription_server') | default(rhsub_server | default(omit, True)) }}"

=======
>>>>>>> Remove reading shell environment in rhel_subscribe
<<<<<<< HEAD
>>>>>>> Remove reading shell environment in rhel_subscribe
=======
=======
>>>>>>> Move repo and subscribe to prerequisites
>>>>>>> Move repo and subscribe to prerequisites
- fail:
    msg: "This role is only supported for Red Hat hosts"
  when: ansible_distribution != 'RedHat'

<<<<<<< HEAD
<<<<<<< HEAD
=======
- fail:
    msg: The rhel_subscription_user variable is required for this role.
  when: rhel_subscription_user is not defined or not rhsub_user is not defined

- fail:
    msg: The rhel_subscription_pass variable is required for this role.
  when: rhel_subscription_pass is not defined or not rhsub_pass is not defined

>>>>>>> Remove reading shell environment in rhel_subscribe
=======
>>>>>>> Move repo and subscribe to prerequisites
- name: Install Red Hat Subscription manager
  yum:
    name: subscription-manager
    state: present
  register: result
<<<<<<< HEAD
<<<<<<< HEAD
  until: result is succeeded

- name: Is host already registered?
  command: "subscription-manager version"
<<<<<<< HEAD
  register: rh_subscribed
  changed_when: False
=======
  until: result | success
>>>>>>> retry package operations
=======
  until: result is succeeded
>>>>>>> Deprecate using Ansible tests as filters

<<<<<<< HEAD
- name: Register host using user/password
=======
- name: Is host already registered?
  command: bash -c "subscription-manager version"
=======
>>>>>>> Move repo and subscribe to prerequisites
  register: rh_subscribed
  changed_when: False

- name: Register host
>>>>>>> Commit to stabalize RHSM operations.  This code is derived from contrib
  redhat_subscription:
    username: "{{ rhsub_user }}"
    password: "{{ rhsub_pass }}"
  register: rh_subscription
<<<<<<< HEAD
<<<<<<< HEAD
  until: rh_subscription is succeeded
  when:
    - "'not registered' in rh_subscribed.stdout"
    - rhsub_user is defined
    - rhsub_pass is defined

<<<<<<< HEAD
- name: Register host using activation key
  redhat_subscription:
    activationkey: "{{ rhsub_ak }}"
    org_id: "{{ rhsub_orgid }}"
  register: rh_subscription
  until: rh_subscription is succeeded
  when:
    - "'not registered' in rh_subscribed.stdout"
    - rhsub_ak is defined
    - rhsub_orgid is defined

- name: Determine if OpenShift Pool Already Attached
  command: "subscription-manager list --consumed --pool-only --matches '*OpenShift*'"
=======
- name: Retrieve the OpenShift Pool ID
  command: subscription-manager list --available --matches="{{ rhsub_pool }}" --pool-only
  register: openshift_pool_id
  until: openshift_pool_id | succeeded
  changed_when: False

- name: Determine if OpenShift Pool Already Attached
  command: subscription-manager list --consumed --matches="{{ rhsub_pool }}" --pool-only
>>>>>>> Remove reading shell environment in rhel_subscribe
  register: openshift_pool_attached
  changed_when: False
<<<<<<< HEAD
  ignore_errors: yes
=======
  when: openshift_pool_id.stdout == ''

- fail:
    msg: "Unable to find pool matching {{ rhsub_pool }} in available or consumed pools"
  when: openshift_pool_id.stdout == '' and openshift_pool_attached is defined and openshift_pool_attached.stdout == ''
>>>>>>> Remove reading shell environment in rhel_subscribe

- name: Attach to OpenShift Pool
  command: "subscription-manager attach --pool {{ rhsub_pool }}"
  register: openshift_pool_attached
  changed_when: "'Successfully attached a subscription' in openshift_pool_attached.stdout"
  when: rhsub_pool not in openshift_pool_attached.stdout

<<<<<<< HEAD
- import_tasks: satellite.yml
=======
- include_tasks: enterprise.yml
>>>>>>> Include Deprecation: Convert to include_tasks
  when:
    - rhsub_server is defined
    - rhsub_server
=======
  until: rh_subscription | succeeded
=======
  until: rh_subscription is succeeded
>>>>>>> Deprecate using Ansible tests as filters
  when:
    - "'not registered' in rh_subscribed.stdout"

- fail:
    msg: 'Unable to register host with Red Hat Subscription Manager'
  when:
    - "'not registered' in rh_subscribed.stdout"
    - rh_subscription.failed

- name: Determine if OpenShift Pool Already Attached
  command: "subscription-manager list --consumed --pool-only --matches '*OpenShift*'"
  register: openshift_pool_attached
  changed_when: False
  ignore_errors: yes

- name: Attach to OpenShift Pool
  command: "subscription-manager attach --pool {{ rhsub_pool }}"
  register: openshift_pool_attached
  changed_when: "'Successfully attached a subscription' in openshift_pool_attached.stdout"
  when: rhsub_pool not in openshift_pool_attached.stdout

- include_tasks: satellite.yml
  when:
<<<<<<< HEAD
    - (rhel_subscription_server or rhsub_server) is defined
    - (rhel_subscription_server or rhsub_server)
>>>>>>> Commit to stabalize RHSM operations.  This code is derived from contrib
=======
    - rhsub_server is defined
    - rhsub_server
>>>>>>> Move repo and subscribe to prerequisites
