---
<<<<<<< HEAD
- name: Install node, clients, and conntrack packages
  package:
    name: "{{ pkg_list | join(',') }}"
    state: present
  register: result
  until: result is succeeded
<<<<<<< HEAD
  vars:
    pkg_list:
    - "{{ openshift_service_type }}-node{{ (openshift_pkg_version | default('')) | lib_utils_oo_image_tag_to_rpm_version(include_dash=True) }}"
    - "{{ openshift_service_type }}-clients{{ (openshift_pkg_version | default('')) | lib_utils_oo_image_tag_to_rpm_version(include_dash=True) }}"
    - conntrack-tools
=======
- when: not openshift.common.is_containerized | bool
  block:
  - name: Install Node package
    package:
      name: "{{ openshift_service_type }}-node{{ (openshift_pkg_version | default('')) | oo_image_tag_to_rpm_version(include_dash=True) }}"
      state: present
    register: result
    until: result is succeeded

  - name: Install sdn-ovs package
    package:
      name: "{{ openshift_service_type }}-sdn-ovs{{ (openshift_pkg_version | default('')) | oo_image_tag_to_rpm_version(include_dash=True) }}"
      state: present
    when:
    - openshift_node_use_openshift_sdn | bool
    register: result
    until: result is succeeded

  - name: Install conntrack-tools package
    package:
      name: "conntrack-tools"
      state: present
    register: result
    until: result is succeeded

- when:
  - openshift.common.is_containerized | bool
  - not l_is_node_system_container | bool
  block:
  - name: Pre-pull node image when containerized
    command: >
      docker pull {{ openshift.node.node_image }}:{{ openshift_image_tag }}
    register: pull_result
    changed_when: "'Downloaded newer image' in pull_result.stdout"
>>>>>>> retry package operations
=======
  with_items:
  - name: "{{ openshift_service_type }}-node{{ (openshift_pkg_version | default('')) | lib_utils_oo_image_tag_to_rpm_version(include_dash=True) }}"
  - name: "{{ openshift_service_type }}-clients{{ (openshift_pkg_version | default('')) | lib_utils_oo_image_tag_to_rpm_version(include_dash=True) }}"
  - name: "conntrack-tools"
  when:
  - not openshift_is_containerized | bool
  - item['install'] | default(True) | bool
>>>>>>> Switch the master to always run with bootstrapping on
