---
- name: Set var to exclude bootstrapped nodes
  set_fact:
    bootstrapped_nodes: "{{ all_nodes | default(false) | ternary([], groups['tag_ocp-bootstrap']) | default([]) }}"

- name: Add node instances to node group
  add_host:
    name: "{{ hostvars[item].gce_name }}"
<<<<<<< HEAD
    groups: nodes, new_nodes
    openshift_node_group_name: "{{ openshift_gcp_node_group_mapping['compute'] }}"
  with_items: "{{ groups['tag_ocp-node'] | default([]) | difference(bootstrapped_nodes) }}"
=======
    groups: masters, etcd
    openshift_node_labels:
      node-role.kubernetes.io/master: "true"
  with_items: "{{ groups['tag_ocp-master'] }}"
>>>>>>> Upgrade to 3.10 with static pods

- name: Add bootstrap node instances as nodes
  add_host:
    name: "{{ item }}"
    groups: nodes, new_nodes
  with_items: "{{ groups['tag_ocp-bootstrap'] | default([]) }}"
  when: all_nodes | default(False)

- name: Add non-bootstrapping master node instances to node group
  add_host:
    name: "{{ hostvars[item].gce_name }}"
    groups: nodes
<<<<<<< HEAD
  with_items: "{{ groups['tag_ocp-master'] | default([]) | difference(bootstrapped_nodes) }}"
=======
  with_items: "{{ groups['tag_ocp-master'] | default([]) | difference(groups['tag_ocp-bootstrap'] | default([])) }}"
>>>>>>> Upgrade to 3.10 with static pods

- name: Add infra node instances to node group
  add_host:
    name: "{{ hostvars[item].gce_name }}"
    groups: nodes, new_nodes
<<<<<<< HEAD
    openshift_node_group_name: "{{ openshift_gcp_node_group_mapping['infra'] }}"
  with_items: "{{ groups['tag_ocp-infra-node'] | default([]) | difference(bootstrapped_nodes) }}"

- name: Add masters to requisite groups
=======
    openshift_node_labels:
      node-role.kubernetes.io/infra: "true"
  with_items: "{{ groups['tag_ocp-infra-node'] | default([]) | difference(groups['tag_ocp-bootstrap'] | default([])) }}"

- name: Add node instances to node group
  add_host:
    name: "{{ hostvars[item].gce_name }}"
    groups: nodes, new_nodes
    openshift_node_bootstrap: False
  with_items: "{{ groups['tag_ocp-node'] | default([]) | difference(groups['tag_ocp-bootstrap'] | default([])) }}"

- name: Add bootstrap node instances
>>>>>>> Upgrade to 3.10 with static pods
  add_host:
    name: "{{ hostvars[item].gce_name }}"
<<<<<<< HEAD
    groups: masters, etcd
    openshift_node_group_name: "{{ openshift_gcp_node_group_mapping['masters'] }}"
  with_items: "{{ groups['tag_ocp-master'] }}"
=======
    groups: bootstrap_nodes
    openshift_node_bootstrap: True
    openshift_is_bootstrapped: True
  with_items: "{{ groups['tag_ocp-node'] | default([]) | intersect(groups['tag_ocp-bootstrap'] | default([])) }}"
<<<<<<< HEAD
  when: not (openshift_node_bootstrap | default(True))
>>>>>>> Switch the master to always run with bootstrapping on
=======

- name: Add bootstrap node instances as nodes
  add_host:
    name: "{{ item }}"
    groups: nodes, new_nodes
    openshift_node_bootstrap: True
    openshift_is_bootstrapped: True
  with_items: "{{ groups['tag_ocp-bootstrap'] | default([]) }}"
  when: all_nodes | default(False)
>>>>>>> Upgrade to 3.10 with static pods
