---
- name: Set node schedulability
  oc_adm_manage_node:
<<<<<<< HEAD
    node: "{{ l_kubelet_node_name | lower }}"
    schedulable: "{{ 'true' if openshift_schedulable | default(true) | bool else 'false' }}"
=======
    node: "{{ openshift.node.nodename | lower }}"
    schedulable: "{{ 'true' if l_openshift_manage_schedulable | bool else 'false' }}"
>>>>>>> Label masters with node-role.kubernetes.io/master. This PR also sets these labels
  retries: 10
  delay: 5
  register: node_schedulable
  until: node_schedulable is succeeded
  when: "'nodename' in openshift.node"
  delegate_to: "{{ openshift_master_host }}"

<<<<<<< HEAD
- name: Wait for sync DS to set annotations on all nodes
  oc_obj:
    state: list
    kind: node
    selector: ""
  register: node_status
  until:
    - node_status.results is defined
    - node_status.results.results is defined
    - node_status.results.results | length > 0
    - node_status.results.results[0]['items']
        | map(attribute='metadata.annotations') | map('list') | flatten
        | select('match', 'node.openshift.io/md5sum') | list | length ==
      node_status.results.results[0]['items'] | length
  retries: 180
  delay: 10
=======
- name: Label nodes
  oc_label:
    name: "{{ openshift.node.nodename }}"
    kind: node
    state: add
    labels: "{{ openshift_node_labels | lib_utils_oo_dict_to_list_of_dict }}"
    namespace: default
  when:
    - "'nodename' in openshift.node"
    - openshift_node_labels | default({}) != {}
  delegate_to: "{{ openshift_master_host }}"

- name: Label master nodes
  oc_label:
    name: "{{ openshift.node.nodename }}"
    kind: node
    state: add
    labels: "{{ openshift_master_node_labels | lib_utils_oo_dict_to_list_of_dict }}"
    namespace: default
  when:
    - "'nodename' in openshift.node"
    - "'oo_masters_to_config' in group_names"
>>>>>>> Label masters with node-role.kubernetes.io/master. This PR also sets these labels
  delegate_to: "{{ openshift_master_host }}"
<<<<<<< HEAD
=======
  vars:
    l_node_labels: "{{ openshift_node_labels | default({}) }}"
    l_master_labels: "{{ openshift_manage_node_is_master | ternary(openshift_master_node_labels, {}) }}"
    l_all_labels: "{{ l_node_labels | combine(l_master_labels) }}"

- import_tasks: set_default_node_role.yml
>>>>>>> Bug 1548641- upgrade now properly sets labels and selectors
