---
- name: Wait for Node Registration
  oc_obj:
    name: "{{ l_kubelet_node_name | lower }}"
    kind: node
    state: list
  register: get_node
  until: "'metadata' in get_node.results.results[0]"
  retries: 50
  delay: 5
  when: "'nodename' in openshift.node"
  delegate_to: "{{ openshift_master_host }}"

<<<<<<< HEAD
<<<<<<< HEAD
- include_tasks: config.yml
=======
- name: Set node schedulability
  oc_adm_manage_node:
    node: "{{ openshift.node.nodename | lower }}"
    schedulable: "{{ 'true' if l_openshift_manage_schedulable | bool else 'false' }}"
  retries: 10
  delay: 5
  register: node_schedulable
  until: node_schedulable is succeeded
  when: "'nodename' in openshift.node"
  delegate_to: "{{ openshift_master_host }}"

- name: Label nodes
  oc_label:
    name: "{{ openshift.node.nodename }}"
    kind: node
    state: add
    labels: "{{ openshift_node_labels | oo_dict_to_list_of_dict }}"
    namespace: default
  when:
    - "'nodename' in openshift.node"
    - openshift_node_labels | default({}) != {}
  delegate_to: "{{ openshift_master_host }}"
>>>>>>> Deprecate using Ansible tests as filters
=======
- include_tasks: config.yml
>>>>>>> Label masters with node-role.kubernetes.io/master. This PR also sets these labels
