---
- name: Install NetworkManager during node_bootstrap provisioning
  package:
    name: NetworkManager
    state: present
  notify: restart NetworkManager
  register: result
<<<<<<< HEAD
  until: result is succeeded
=======
  until: result | success
>>>>>>> retry package operations

- import_tasks: network-manager.yml
