---
<<<<<<< HEAD
openshift_node_group_cloud_provider: "{{ openshift_cloudprovider_kind | default('') }}"
openshift_node_group_network_plugin_default: "{{ os_sdn_network_plugin_name }}"
=======
openshift_node_groups:
- name: node-config-master
  labels:
  - 'node-role.kubernetes.io/master=true'
  edits: []
- name: node-config-infra
  labels:
  - 'node-role.kubernetes.io/infra=true'
  edits: []
- name: node-config-compute
  labels:
  - 'node-role.kubernetes.io/compute=true'
  edits: []

l_openshift_node_group_master: "{{ openshift_node_group_master | default('node-config-master') }}"

openshift_node_group_edits: []
openshift_node_group_namespace: openshift-node
openshift_node_group_labels: []

openshift_use_crio: False
l_crio_use_new_var_sock: "{{ openshift_version | version_compare('3.9', '>=') }}"
l_crio_var_sock: "{{ l_crio_use_new_var_sock | ternary('/var/run/crio/crio.sock', '/var/run/crio.sock') }}"

openshift_node_group_cloud_provider: "{{ openshift_cloudprovider_kind | default(None) }}"
openshift_node_group_network_plugin_default: "{{ os_sdn_network_plugin_name | default('redhat/openshift-ovs-subnet') }}"
>>>>>>> Upgrade to 3.10 with static pods
openshift_node_group_network_plugin: "{{ openshift_node_group_network_plugin_default }}"
openshift_node_group_node_data_dir_default: "{{ openshift_data_dir | default('/var/lib/origin') }}"
openshift_node_group_node_data_dir: "{{ openshift_node_group_node_data_dir_default }}"

openshift_imageconfig_format: "{{ oreg_url | default(l_osm_registry_url_default) }}"

openshift_node_group_use_persistentlocalvolumes: "{{ openshift_persistentlocalstorage_enabled | default(False) | bool }}"
openshift_node_group_name: 'node-config-compute'

l_openshift_node_group_labels: []

openshift_node_iptables_sync_period: '30s'
