---
# l_repo_hosts is passed in via prerequisites.yml.

- name: Setup yum repositories for all hosts
  hosts: "{{ l_repo_hosts | default('all:!all') }}"
  gather_facts: no
  tasks:
  - name: subscribe instances to Red Hat Subscription Manager
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> Migrate to import_role for static role inclusion
    import_role:
      name: rhel_subscribe
    when:
    - ansible_distribution == 'RedHat'
    - openshift_deployment_type == 'openshift-enterprise'
<<<<<<< HEAD
    - (rhsub_user is defined and rhsub_pass is defined) or (rhsub_ak is defined and rhsub_orgid is defined)
=======
    include_role:
      name: rhel_subscribe
    when:
    - ansible_distribution == 'RedHat'
    - deployment_type == 'openshift-enterprise'
<<<<<<< HEAD
    - (rhel_subscription_user or rhsub_user) is defined
    - (rhel_subscription_password or rhsub_pass) is defined
>>>>>>> Commit to stabalize RHSM operations.  This code is derived from contrib
=======
    - rhsub_user | default(False)
    - rhsub_pass | default(False)
>>>>>>> Move repo and subscribe to prerequisites
=======
    - rhsub_user is defined
    - rhsub_pass is defined
>>>>>>> Migrate to import_role for static role inclusion
  - name: initialize openshift repos
    import_role:
      name: openshift_repos
