---
# TODO: abstract me into a relatively generic task
<<<<<<< HEAD
- name: Verify that the catalog api server is running
=======
- name: Verify that the web console is running
>>>>>>> Switch the master to always run with bootstrapping on
  command: >
    curl -k https://apiserver.kube-service-catalog.svc/healthz
  args:
    # Disables the following warning:
    # Consider using get_url or uri module rather than running curl
    warn: no
  register: endpoint_health
  until: endpoint_health.stdout == 'ok'
<<<<<<< HEAD
  retries: "{{ openshift_service_catalog_retries }}"
=======
  retries: 60
>>>>>>> Switch the master to always run with bootstrapping on
  delay: 10
  changed_when: false
  # Ignore errors so we can log troubleshooting info on failures.
  ignore_errors: yes

# Log the result of `oc status`, `oc get pods`, `oc get events`, and `oc logs deployment/webconsole` for troubleshooting failures.
- when: endpoint_health.stdout != 'ok'
  block:
  - name: Check status in the kube-service-catalog namespace
    command: >
      {{ openshift_client_binary }} status --config=/etc/origin/master/admin.kubeconfig -n kube-service-catalog
    register: endpoint_status
    ignore_errors: true
  - debug:
      msg: "{{ endpoint_status.stdout_lines }}"
  - name: Get pods in the kube-service-catalog namespace
    command: >
      {{ openshift_client_binary }} get pods --config=/etc/origin/master/admin.kubeconfig -n kube-service-catalog -o wide
    register: endpoint_pods
    ignore_errors: true
  - debug:
      msg: "{{ endpoint_pods.stdout_lines }}"
  - name: Get events in the kube-service-catalog namespace
    command: >
      {{ openshift_client_binary }} get events --config=/etc/origin/master/admin.kubeconfig -n kube-service-catalog
    register: endpoint_events
    ignore_errors: true
  - debug:
      msg: "{{ endpoint_events.stdout_lines }}"
  - name: Get pod logs
    command: >
<<<<<<< HEAD
      {{ openshift_client_binary }} logs daemonset/apiserver --tail=200 --config=/etc/origin/master/admin.kubeconfig -n kube-service-catalog
=======
      {{ openshift_client_binary }} logs daemonset/apiserver --tail=50 --config=/etc/origin/master/admin.kubeconfig -n kube-service-catalog
>>>>>>> Switch the master to always run with bootstrapping on
    register: endpoint_log
    ignore_errors: true
  - debug:
      msg: "{{ endpoint_log.stdout_lines }}"

- when: endpoint_health.stdout != 'ok'
  block:
  - name: Report errors
    fail:
      msg: Catalog install failed.
