---
- name: Install docker gc
  hosts: oo_first_master
  gather_facts: false
  roles:
  - openshift_facts
  tasks:
<<<<<<< HEAD
  - import_role:
      name: openshift_docker_gc
    when:
    - openshift_crio_enable_docker_gc | bool
=======
    - import_role:
        name: openshift_docker_gc
>>>>>>> Migrate to import_role for static role inclusion
